### ISSUE TITLE
Bug [3.0.0-rc2] Service generated even when `ignore: true` is specified

### ISSUE THREAD

**Issue by SteelAlloy** [metal3d/katenary#107]
The `ignore` option is ignored when enabled.

```shell
❯ katenary convert -c compose.yaml -o ./chart
❯ ls chart/templates/gitlab-postgres 
configmap.yaml  deployment.yaml  gitlab_postgres.volumeclaim.yaml  service.yaml
```

Reproducible example  :

### `compose.yaml`
```yaml
services:
  gitlab:
    image: gitlab/gitlab-ee:17.4.3-ee.0
    restart: always
    container_name: gitlab
    environment:
      GITLAB_ROOT_PASSWORD: "FbHwagnIboY8Rv"
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url = 'http://git.127.0.0.1.nip.io';
        # Postgres
        postgresql['enable'] = false;
        gitlab_rails['db_adapter'] = 'postgresql';
        gitlab_rails['db_encoding'] = 'utf8';
        gitlab_rails['db_host'] = 'gitlab-postgres';
        gitlab_rails['db_port'] = 5432;
        gitlab_rails['db_username'] = 'gitlab';
        gitlab_rails['db_password'] = 'gitlab';
    ports:
      - '80:80'
      - '22:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - network
  gitlab-postgres:
    image: postgres:15
    container_name: gitlab-postgres
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab
      POSTGRES_DB: gitlabhq_production
    ports:
      - '5432:5432'
    shm_size: 128mb
    networks:
      - network
    volumes:
      - 'gitlab_postgres:/var/lib/postgresql/data'

networks:
  network:
    driver: bridge
    name: gitlab_network

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_postgres:
```

### `katenary.yaml`
```yaml
# yaml-language-server: $schema=./katenary.schema.json

gitlab:
  main-app: true
  ingress:
    hostname: git.127.0.0.1.nip.io
    port: 80
  secrets:
    - GITLAB_ROOT_PASSWORD
    - GITLAB_OMNIBUS_CONFIG
  values:
    - GITLAB_ROOT_PASSWORD
    - GITLAB_OMNIBUS_CONFIG
postgres:
  ignore: true
```
