### ISSUE TITLE
Wrong syntax with TCP healthcheck

### ISSUE THREAD

**Issue by adrian-salas** [metal3d/katenary#30]
Hello,

After using the following label:
`katenary.io/healthcheck: tcp://localhost:3306`

The generated output is the following:

```
livenessProbe:
  tcp:
    port: 3306
            ...
```

However the syntax is: `tcpSocket` (https://kubernetes.io/fr/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#d%C3%A9finir-une-tcp-liveness-probe)
